BEGIN;

ALTER TABLE transactions DROP CONSTRAINT IF EXISTS fk_event;
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS fk_user;
ALTER TABLE pricings DROP CONSTRAINT IF EXISTS fk_event;
ALTER TABLE tickets DROP CONSTRAINT IF EXISTS fk_event;
ALTER TABLE tickets DROP CONSTRAINT IF EXISTS fk_transaction;
ALTER TABLE submissions DROP CONSTRAINT IF EXISTS fk_event;
ALTER TABLE submissions DROP CONSTRAINT IF EXISTS fk_user;
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS fk_user;
COMMIT;